server:
  port: 8090
  application:
    name: cloudweb

spring: 
  cloud:
    config:
      uri: http://${config.server.ip}:${config.server.port}
      name: cloudservice
      profile: ${app.profile:test}

#service discovery url
eureka: 
  client:
    serviceUrl:
      defaultZone: http\://localhost\:8761/eureka/

#ribbon config
cloudservice:
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 10000