spring: 
  port: 9999

spring: 
  application: 
    name: cloudhello
  cloud:
    config:
      uri: http://${config.server.ip}:${config.server.port}
      name: cloudhello
      profile: ${app.profile:test}